services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    working_dir: /app
    volumes:
      - ./app/:/app/
    ports:
      - "5022:5022"
    command: ["dotnet", "watch", --urls=http://0.0.0.0:5022]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5022
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
