services:
    
  app:
    build: .
    image: digital-wallet
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - app-network

  migrations:
    image: digital-wallet-migrations
    profiles:
      - optional
    build: 
      dockerfile: mig.Dockerfile
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
