services:
  app:
    build: .
    image: digital-wallet
    ports:
      - "8080:8080"
    networks:
      - app-network
  db:
    image: postgres:latest
    ports:
      - "5488:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
